travis:
  secure:
    BINSTAR_TOKEN: PDUxPRnRksFbfZc96W9YKkILLD4OQEhjpOj3hlu6q4h9g4mNm2IfkJXhXq1Lg0cMKoKYVymO+G44ZPrnxgUEY4pLGYT2/Yfnd+1xOF0b7bf6bjSkHDJlzDgAqAl9PLR2t7aZY5p7WxSY/0aoARDazytpefjq4ThNYdfCieJtzxWvKbNeMFe3zOplACK6UcGMp8n3imyMKpS3j4KK7bveLnXihFDb/y8BrFvkfqsJFJHFqOEikUYgIb3jG3XKQ+EgrAB6DEvVtEaAig7cQkSer1GL59+WEyi27Uj9+WIgD6ft4EM3yx7pu+frxwYw5FmoFzfZrPc63OBFoWJimRkqUvfBh8DXTaHEjeddJ9RGIzYncrjSZiuhhhDI+wjP9ASWzXaqdhiBMV8jUiuwdgcUuFrynMmnOsIcXB5QKGrS4GQXTE35kcsLYLvV4wkoDw1VhoQ6qrpkp4Jj9yD+U2yZBPlo2Sa8Yb+HZBby4b7b/oemvNkSBp17felvV86HO2RS63jVd36OWivNBpvEszt+d2VucP69j/akm8pKTNEcCyIqK6Tp7ya/xS6yO0xXTfPsVVkmCiPd/sQG2ty13omqKB6in2T4z4oX5+SNeAMYUJLgvHF6qRiBV4LjjSK1wJnz4nyqAwZTI5RIA5XKyLorBg7wNuTX9nNMdXq6onLN7zk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
