travis:
  secure:
    BINSTAR_TOKEN: K7G2ZtzX3vks3y/2/Rbx3BENNRhSPygspAOBCb/nZg3EsR71pKONy346KJZ85HzE+DoR4UnFSFPaK1E7dL611dSi8/EbmKtk9BP9ngVmK0BXVdnEtsizuq4YAnyYyX1u9NcFC8uizEHC+QaeEgE77JnB/yVEJCb8+OSi8asAlAFzsDVa75dkkM/G6GYqM6kwh/yKgM64Emhkukz5KZPbRfV64j7ZYnrvOqxyjGWHGeo1IO2ZW6vHjRYwVQ4uSzX6rqp63VArY1h17F8lA1pOPm91byZohC8agCkd/zm4CMncIEQ8NWWoc5zPzUGdhrNDK0HYrMJm5yjJFAArf1uBztjc10sPpQ+zraeuluAq/M8K6ezzqLT8YQ49USg3cSHocKM83kmhYyzD0wDBmQo/aGkRZZDABbfGKoTeWY81QbMGAW0n7JEIi/Q/SXq5JXxM091A6lxdbZuuEqFHZdACMte/aaIp4pxbsy1N1OvGOxq5UyiwfaE8mRh9/gzI5hVVW1gPyQmOvnobhuCeUyuKu6IhOZQL+9VWxvOC1SIgHZ8MxrxQ53+YLmWuXb3mdZRV6LIKEfg7x6Zz++mgR4IycQdaJew4XV2zsWxBIUG2YpX4BCkyy1jlrM51ZBWu5nV8JRPTuvosWyMD+iQNjWpTQm51vX1RDvQna5lpE58YYXA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
