travis:
  secure:
    BINSTAR_TOKEN: XSHCXCVBqyWt9virzwPCdj6+qco+D/EMIBedE1HJoW5fa3bpH7mCJMVC+a/xw8TYy0Xincs5qEzCXZvaoB0H9BnAGOnd+YfrMKlh1s3l7DbToxD7wbG0r8pzZ91eRmp1N7QL9XNL6EAtNKYO5iefltzfWN5f14pPBTAPUoEI3MfmXLDML9u+V2OHjlRyfOtPeSA0XCXx9jFYNIi/EI8If0R0QXivn1vML5Ir6VEQGO76m2Ppst/cuquWusSp0c6K4thEiOJFI7QTg2s/HCFtcZaEZjUsCyjkwInfeZrpFBuM2UEjAe88erXeESnU5m8EtUxmCArHfrDZZrSd7s2kY8T7B+HBH3pvfrrYmKMn4atZ6i42XaA2qehtqXZ7G0ayt4M0GN7/EVbu4e96fNvUULnZmni05OEb1SqDw9ek2pA9JYhXLgZsu0dkUQRAYm4q4I6pAb2Ew+j9q1jLeQZNt6C1NBWpXubPAnxa4xSRCT9M/3WbVQSGjkW43bDIH1Op+SkAMF+vD8sYWvY5kJKjUEL083OvB0CA5xyAWRYWbo6e8vlKbeKZAjZUxLwEZKZ+xJUjzZO7x+PNh0iAEQCvlY6lEl2xggX/IGbiU2QsKtG7Xgh/TNtPoEI+PZiOKxejL3Ecsb0q45aL6JXFlkPr8WKczBmlQx19Zb5G3QE/BAk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
