travis:
  secure:
    BINSTAR_TOKEN: NoGLzOUDnxdU/aPJTZPAI180GHaPfwqRk0e9ZYWfvZNm6CsU7Fx8U35Lzc+r/V7pVKSZ+T6QGQurNbMMllw2QmTFd7U+wfFDwGpS3CZzUsJInpmLtpqlZKS25gyI40htS8Ha+XW/qAL9qFSnRVzTyMaehyVw3ez25bwW/z+hn4YgUbYb8t0bAvYMMSUfFjRJtjcWF5vQXSs5s5O9Gf034SIrbntVv4y1ens6vfQcnu81WLKNEJQLELM8j8qJ07L32jLF9uW4lOKmV49iEo483opWMuV+DYg+6M7tGRHsrvCccFY8GEJPLvBcaIlzaeseHTu/xor3aosrJ7AbX5sLiQn+PE0q84OxfcC7s+d0+tgjbz5wWATDcy+0aDQmAc1rwDJ50ZhpTSun+UZGyhFgMasUlrjA+XVhXJqfgBVRKmg02vnzUktpSifcoNg7DXflZYNNRnHlxvgAClFUPW41ck75bYFH7b757v/hw6/tZ7RFLFCv9uTWwWVCN2GWzvcBpITZbOQ75U6qWTOXonGyWBf+B3pRqRiC0+QArVhMoAxFg+2MemKFGsiiCTnl3UTe3lyAa09Pzc2qRE4DGUMaEyA2/5hPmdd0PM+vKHOyl42j84edA0OjKPgU1YakV5QCiFc8dXlu6JkC18YLyEl9nsqbI0o6LOE4hAh/fztr8GE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
